const char *custom_reg_name[243] = {
    "bltddat", /* 0x000 */
    "dmaconr",
    "vposr",
    "vhposr",
    "dskdatr",
    "joy0dat",
    "joy1dat",
    "clxdat",
    "adkconr", /* 0x010 */
    "pot0dat",
    "pot1dat",
    "potinp",
    "serdatr",
    "dskbytr",
    "intenar",
    "intreqr",
    "dskpt",   /* 0x020 */
    "dskptl",
    "dsklen",
    "dskdat",
    "refptr",
    "vposw",
    "vhposw",
    "copcon",
    "serdat",  /* 0x030 */
    "serper",
    "potgo",
    "joytest",
    "strequ",
    "strvbl",
    "strhor",
    "strlong",
    "bltcon0", /* 0x040 */
    "bltcon1",
    "bltafwm",
    "bltalwm",
    "bltcpt",
    "bltcptl",
    "bltbpt",
    "bltbptl",
    "bltapt",  /* 0x050 */
    "bltaptl",
    "bltdpt",
    "bltdptl",
    "bltsize",
    "cust[5a]",
    "cust[5c]",
    "cust[5e]",
    "bltcmod", /* 0x060 */
    "bltbmod",
    "bltamod",
    "bltdmod",
    "cust[68]",
    "cust[6a]",
    "cust[6c]",
    "cust[6e]",
    "bltcdat", /* 0x070 */
    "bltbdat",
    "bltadat",
    "cust[76]",
    "cust[78]",
    "cust[7a]",
    "cust[7c]",
    "dsksync",
    "cop1lc",  /* 0x080 */
    "cop1lcl",
    "cop2lc",
    "cop2lcl",
    "copjmp1",
    "copjmp2",
    "copins",
    "diwstrt",
    "diwstop", /* 0x090 */
    "ddfstrt",
    "ddfstop",
    "dmacon",
    "clxcon",
    "intena",
    "intreq",
    "adkcon",
    "aud0lc",  /* 0x0a0 */
    "aud0lcl",
    "aud0len",
    "aud0per",
    "aud0vol",
    "aud0dat",
    "cust[ac]",
    "cust[ee]",
    "aud1lc",  /* 0x0b0 */
    "aud1lcl",
    "aud1len",
    "aud1per",
    "aud1vol",
    "aud1dat",
    "cust[bc]",
    "cust[be]",
    "aud2lc",  /* 0x0c0 */
    "aud2lcl",
    "aud2len",
    "aud2per",
    "aud2vol",
    "aud2dat",
    "cust[cc]",
    "cust[ce]",
    "aud3lc",  /* 0x0d0 */
    "aud3lcl",
    "aud3len",
    "aud3per",
    "aud3vol",
    "aud3dat",
    "cust[dc]",
    "cust[de]",
    "bpl1pt",  /* 0x0e0 */
    "bpl1ptl",
    "bpl2pt",
    "bpl2ptl",
    "bpl3pt",
    "bpl3ptl",
    "bpl4pt",
    "bpl4ptl",
    "bpl5pt",  /* 0x0f0 */
    "bpl5ptl",
    "bpl6pt",
    "bpl6ptl",
    "bpl7pt",
    "bpl7ptl",
    "bpl8pt",
    "bpl8ptl",
    "bplcon0", /* 0x100 */
    "bplcon1",
    "bplcon2",
    "bplcon3",
    "bpl1mod",
    "bpl2mod",
    "bplcon4",
    "clxcon2",
    "bpl1dat", /* 0x110 */
    "bpl2dat",
    "bpl3dat",
    "bpl4dat",
    "bpl5dat",
    "bpl6dat",
    "bpl7dat",
    "bpl8dat",
    "spr0pt",  /* 0x120 */
    "spr0ptl",
    "spr1pt",
    "spr1ptl",
    "spr2pt",
    "spr2ptl",
    "spr3pt",
    "spr3ptl",
    "spr4pt",  /* 0x130 */
    "spr4ptl",
    "spr5pt",
    "spr5ptl",
    "spr6pt",
    "spr6ptl",
    "spr7pt",
    "spr7ptl",
    "spr0pos", /* 0x140 */
    "spr0ctl",
    "spr0data",
    "spr0datb",
    "spr1pos",
    "spr1ctl",
    "spr1data",
    "spr1datb",
    "spr2pos", /* 0x150 */
    "spr2ctl",
    "spr2data",
    "spr2datb",
    "spr3pos",
    "spr3ctl",
    "spr3data",
    "spr3datb",
    "spr4pos", /* 0x160 */
    "spr4ctl",
    "spr4data",
    "spr4datb",
    "spr5pos",
    "spr5ctl",
    "spr5data",
    "spr5datb",
    "spr6pos", /* 0x170 */
    "spr6ctl",
    "spr6data",
    "spr6datb",
    "spr7pos",
    "spr7ctl",
    "spr7data",
    "spr7datb",
    "color00", /* 0x180 */
    "color01",
    "color02",
    "color03",
    "color04",
    "color05",
    "color06",
    "color07",
    "color08", /* 0x190 */
    "color09",
    "color0a",
    "color0b",
    "color0c",
    "color0d",
    "color0e",
    "color0f",
    "color10", /* 0x1a0 */
    "color11",
    "color12",
    "color13",
    "color14",
    "color15",
    "color16",
    "color17",
    "color18", /* 0x1b0 */
    "color19",
    "color1a",
    "color1b",
    "color1c",
    "color1d",
    "color1e",
    "color1f",
    "htotal",  /* 0x1c0 */
    "hsstop",
    "hbstrt",
    "hbstop",
    "vtotal",
    "vsstop",
    "vbstrt",
    "vbstop",
    "sprhstrt",/* 0x1d0 */
    "sprhstop",
    "bplhstrt",
    "bplhstop",
    "hhposw",
    "hhposr",
    "beamcon0",
    "hsstrt",
    "vsstrt",  /* 0x1e0 */
    "hcenter",
    "diwhigh", /* 0x1e4 */
};

const char *cia_reg_name[16] = {
    "pra",
    "prb",
    "ddra",
    "ddrb",
    "talo",
    "tahi",
    "tblo",
    "tbhi",
    "todlow",
    "todmid",
    "todhi",
    "[b00]",
    "sdr",
    "icr",
    "cra",
    "crb"
};

/*
 * Local variables:
 * mode: C
 * c-file-style: "Linux"
 * c-basic-offset: 4
 * tab-width: 4
 * indent-tabs-mode: nil
 * End:
 */
