X(unformatted, "Unformatted")
X(amigados, "AmigaDOS")
X(amigados_extended, "AmigaDOS Extended")
X(copylock, "Copylock")
X(psygnosis_a, "Psygnosis A")
X(psygnosis_b, "Psygnosis B")
X(rnc_pdos, "RNC PDOS")
X(core_design, "Core Design")
X(gremlin, "Gremlin Graphics")
X(rainbird, "Rainbird")
X(archipelagos, "Archipelagos")
X(longtrack, "Protection Long Track")
X(alienbreed_protection, "Alien Breed Copy Protection")
X(blue_byte, "Blue Byte")
X(ikplus, "IK+")
X(virus, "Virus")
X(sensible, "Sensible Software")
X(rtype, "R-Type")
X(raw, "Raw")
